In [ ]:
import pandas as pd
import numpy as np
# 아래에 csv 중에는 gens랑 weather만 돌리면 됨

### gens : 전지역 시간대별 발전량 
* == 2. 태양광 발전소별 일단위 발전량 조회

In [ ]:
gens = pd.read_csv('/content/drive/MyDrive/POSTECH 태양광 발전량 예측/DATA/gens.csv')
gens = pd.DataFrame(gens)
gens.head(5)

# (363707, 3)
# id = 0 : 광명시 - 2280
# id = 1~20 : 타지역
# time : 한 시간 단위 해당 시간대의 발전량 
# id = 0 : 2022.07.21 ~ 2022.10.23
# id = 1~20 : 2020.10.01 ~ 2022.10.23

   id                       time  amount
0   0  2022-07-21 01:00:00+09:00     0.0
1   0  2022-07-21 02:00:00+09:00     0.0
2   0  2022-07-21 03:00:00+09:00     0.0
3   0  2022-07-21 04:00:00+09:00     0.0
4   0  2022-07-21 05:00:00+09:00     0.0

In [ ]:
gens['id'].value_counts()

10    18072
11    18072
19    18072
18    18072
17    18072
16    18072
15    18072
14    18072
13    18072
12    18072
20    18072
9     18072
8     18072
7     18072
6     18072
5     18072
4     18072
3     18072
2     18072
1     18059
0      2280
Name: id, dtype: int64

### envs : 광명시 기상데이터
* == -1. 광명발전소의 센서 데이터 조회

In [ ]:
envs = pd.read_csv('/content/drive/MyDrive/POSTECH 태양광 발전량 예측/DATA/envs.csv')
envs = pd.DataFrame(envs)
envs.head(5)

# (26727, 4)
# id = 0 광명시 only : 2022.07.21 ~ 2022.10.23
# time : 기상센서 계측 시간
# nins : 일사량
# mtemp : 태양전지 모듈 표현 온도 계측 값(섭씨)

   id                       time  nins  mtemp
0   0  2022-07-21 00:03:55+09:00   0.0   23.9
1   0  2022-07-21 00:08:42+09:00   0.0   23.9
2   0  2022-07-21 00:13:56+09:00   0.0   23.9
3   0  2022-07-21 00:18:43+09:00   0.0   23.9
4   0  2022-07-21 00:23:56+09:00   0.0   23.9

In [ ]:
envs['time']

0        2022-07-21 00:03:55+09:00
1        2022-07-21 00:08:42+09:00
2        2022-07-21 00:13:56+09:00
3        2022-07-21 00:18:43+09:00
4        2022-07-21 00:23:56+09:00
                   ...
26722    2022-10-23 23:39:34+09:00
26723    2022-10-23 23:44:21+09:00
26724    2022-10-23 23:49:34+09:00
26725    2022-10-23 23:54:21+09:00
26726    2022-10-23 23:59:34+09:00
Name: time, Length: 26727, dtype: object

### weathers1
* == 3-1. 기상데이터1의 일단위 기상 관측데이터 조회

In [ ]:
weathers1 = pd.read_csv('/content/drive/MyDrive/POSTECH 태양광 발전량 예측/DATA/weathers1.csv')
weathers1 = pd.DataFrame(weathers1)
weathers1.head(5)

# (403028, 13)
# id = 1~21 : 기상관측소 ID
# time : 2020.10.01 ~ 2022.10.23 한시간 단위
# temperature : 기온
# humidity : 습도 %
# dew_point : 이슬점 온도
# wind_dir : 풍향 (각도)
# uv_idx : 자외선 강도 (0~12)
# visibility : 시정 거리 (KM)
# cloudiness : 구름으로 덮인 하늘의 백분율 %
# ceiling : 구름의 가장 낮은 층의 위치 (m)
# pressure : 기압(mb)
# precip_1h : 강수량(mm)

,id,time,temperature,humidity,dew_point,wind_dir,wind_spd,uv_idx,visibility,cloudiness,ceiling,pressure,precip_1h
0,1,2020-10-01T00:00:00+09:00,16.5,100.0,16.4,338.0,5.7,0.0,16.1,74.0,9144.0,1011.0,0.0
1,1,2020-10-01T01:01:00+09:00,16.7,88.0,14.7,315.0,5.3,0.0,16.1,31.0,9144.0,1011.0,0.0
2,1,2020-10-01T02:01:00+09:00,16.5,95.0,15.8,45.0,5.0,0.0,14.5,18.0,9144.0,1012.0,0.0
3,1,2020-10-01T03:00:00+09:00,16.1,92.0,14.8,23.0,3.7,0.0,14.5,11.0,9144.0,1012.0,0.0
4,1,2020-10-01T04:00:00+09:00,15.8,87.0,13.8,270.0,4.7,0.0,17.7,51.0,9144.0,1012.0,0.0

In [ ]:
weathers1[weathers1['id'] == 21]

,id,time,temperature,humidity,dew_point,wind_dir,wind_spd,uv_idx,visibility,cloudiness,ceiling,pressure,precip_1h
383521,21,2020-10-01T00:00:00+09:00,16.0,98.0,15.7,315.0,6.4,0.0,16.1,62.0,9144.0,1011.8,0.0
383522,21,2020-10-01T01:01:00+09:00,15.5,91.0,14.1,68.0,3.7,0.0,17.7,0.0,9754.0,1011.5,0.0
383523,21,2020-10-01T02:01:00+09:00,15.1,100.0,15.1,158.0,4.4,0.0,12.9,12.0,9144.0,1011.5,0.0
383524,21,2020-10-01T03:00:00+09:00,14.6,100.0,14.6,135.0,4.0,0.0,11.3,24.0,9144.0,1012.2,0.0
383525,21,2020-10-01T04:00:00+09:00,14.1,100.0,14.1,90.0,3.7,0.0,14.5,88.0,8534.0,1011.8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
403023,21,2022-10-23T20:58:00+09:00,12.9,67.0,6.9,293.0,9.4,0.0,48.3,0.0,12192.0,1020.4,0.0
403024,21,2022-10-23T21:58:00+09:00,12.7,44.0,0.7,315.0,9.3,0.0,24.1,0.0,12192.0,1019.6,0.0
403025,21,2022-10-23T22:07:00+09:00,12.9,43.0,0.7,315.0,9.3,0.0,49.9,0.0,12192.0,1019.9,0.0
403026,21,2022-10-23T22:58:00+09:00,12.6,59.0,4.9,338.0,10.5,0.0,49.9,1.0,12192.0,1019.9,0.0
403027,21,2022-10-23T23:58:00+09:00,11.0,71.0,5.9,315.0,5.4,0.0,49.9,2.0,12192.0,1019.3,0.0

### weathers2
* == 3-2. 기상데이터2의 일단위 기상 관측데이터 조회

In [ ]:
weathers2 = pd.read_csv('/content/drive/MyDrive/POSTECH 태양광 발전량 예측/DATA/weathers2.csv')
weathers2 = pd.DataFrame(weathers2)
weathers2.head(5)

# (607022, 9)
# id = 1~17 : 기상 관측소 ID
# time : 2020.10.01 ~ 2020.10.23 30분 단위
# temperature : 기온
# humidity : 습도 %
########### dew_point : 이슬점 온도
# wind_dir : 풍향 (각도)
# wind_spd : 풍속 (m/s)
########### uv_idx : 자외선 강도 (0~12)
########### visibility : 시정 거리 (KM)
########### cloudiness : 구름으로 덮인 하늘의 백분율 %
########### ceiling : 구름의 가장 낮은 층의 위치 (m)
########### pressure : 기압(mb)
# precip_1h : 강수량(mm)

,id,time,temperature,humidity,wind_dir,wind_spd,cloudiness,pressure,precip_1h
0,1,2020-10-01T00:00:43+09:00,17.29,100.0,79.0,1.18,1.0,1012.0,0.0
1,1,2020-10-01T00:30:42+09:00,17.29,88.0,93.0,1.74,75.0,1011.0,0.0
2,1,2020-10-01T01:00:42+09:00,17.29,88.0,93.0,1.74,75.0,1011.0,0.0
3,1,2020-10-01T01:30:41+09:00,17.37,77.0,120.0,2.20,1.0,1012.0,0.0
4,1,2020-10-01T02:00:44+09:00,17.37,77.0,120.0,2.20,1.0,1012.0,0.0

In [ ]:
weathers2[weathers2['id'] == 1]

,id,time,temperature,humidity,wind_dir,wind_spd,cloudiness,pressure,precip_1h
0,1,2020-10-01T00:00:43+09:00,17.29,100.0,79.0,1.18,1.0,1012.0,0.0
1,1,2020-10-01T00:30:42+09:00,17.29,88.0,93.0,1.74,75.0,1011.0,0.0
2,1,2020-10-01T01:00:42+09:00,17.29,88.0,93.0,1.74,75.0,1011.0,0.0
3,1,2020-10-01T01:30:41+09:00,17.37,77.0,120.0,2.20,1.0,1012.0,0.0
4,1,2020-10-01T02:00:44+09:00,17.37,77.0,120.0,2.20,1.0,1012.0,0.0
...,...,...,...,...,...,...,...,...,...
35698,1,2022-10-23T21:30:41+09:00,11.48,50.0,300.0,2.06,0.0,1020.0,0.0
35699,1,2022-10-23T22:00:48+09:00,8.83,44.0,320.0,4.15,2.0,1021.0,0.0
35700,1,2022-10-23T22:30:41+09:00,10.52,57.0,290.0,3.09,0.0,1020.0,0.0
35701,1,2022-10-23T23:00:55+09:00,7.83,47.0,320.0,3.94,2.0,1021.0,0.0
35702,1,2022-10-23T23:30:42+09:00,10.16,57.0,280.0,2.06,0.0,1021.0,0.0

### weather3
* == 3-3. 기상데이터3의 일단위 기상 관측데이터 조회

In [ ]:
weathers3 = pd.read_csv('/content/drive/MyDrive/POSTECH 태양광 발전량 예측/DATA/weathers3.csv')
weathers3 = pd.DataFrame(weathers3)
weathers3.head(5)

# (345423, 7)
# id = 1~21 : 기상 관측소 ID
# time : 2021.11.24 ~ 2022.10.23 한시간 단위
# temperature : 기온
# humidity : 습도 %
########### dew_point : 이슬점 온도
# wind_dir : 풍향 (각도)
## 추가 : wind_spd : 풍속 (m/s)
########### uv_idx : 자외선 강도 (0~12)
########### visibility : 시정 거리 (KM)
# cloudiness : 구름으로 덮인 하늘의 백분율 %
########### ceiling : 구름의 가장 낮은 층의 위치 (m)
# pressure : 기압(mb)
# precip_1h : 강수량(mm)

,id,time,temperature,humidity,wind_dir,wind_spd,precip_1h
0,1,2021-11-23T23:00:00+09:00,1.5,61.0,241.0,3.5,0.0
1,1,2021-11-24T00:00:00+09:00,1.4,62.0,260.0,2.7,0.0
2,1,2021-11-24T01:00:00+09:00,1.5,64.0,275.0,2.1,0.0
3,1,2021-11-24T02:00:00+09:00,1.7,68.0,283.0,1.4,0.0
4,1,2021-11-24T03:00:00+09:00,1.4,69.0,324.0,1.5,0.0

In [ ]:
weathers1[weathers1['id'] == 3]

,id,time,temperature,humidity,dew_point,wind_dir,wind_spd,uv_idx,visibility,cloudiness,ceiling,pressure,precip_1h
39821,3,2020-10-01T00:00:00+09:00,15.7,91.0,14.2,135.0,6.6,0.0,16.1,5.0,9144.0,1012.0,0.0
39822,3,2020-10-01T01:01:00+09:00,15.3,84.0,12.6,0.0,1.9,0.0,16.1,25.0,9144.0,1012.0,0.0
39823,3,2020-10-01T02:01:00+09:00,14.8,94.0,13.9,315.0,4.1,0.0,14.5,17.0,9144.0,1013.0,0.0
39824,3,2020-10-01T03:00:00+09:00,14.4,95.0,13.6,68.0,4.3,0.0,14.5,39.0,9144.0,1013.0,0.0
39825,3,2020-10-01T04:00:00+09:00,14.1,92.0,12.7,0.0,1.9,0.0,19.3,88.0,9144.0,1013.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58798,3,2022-10-23T19:57:00+09:00,15.2,68.0,9.3,315.0,3.6,0.0,14.5,3.0,12192.0,1018.9,0.0
58799,3,2022-10-23T20:58:00+09:00,14.6,69.0,9.0,293.0,5.8,0.0,16.1,6.0,12192.0,1018.3,0.0
58800,3,2022-10-23T21:58:00+09:00,14.5,52.0,4.7,293.0,5.6,0.0,22.5,63.0,12192.0,1018.0,0.0
58801,3,2022-10-23T22:58:00+09:00,12.4,67.0,6.4,293.0,0.4,0.0,24.1,1.0,12192.0,1017.1,0.0
58802,3,2022-10-23T23:58:00+09:00,11.5,66.0,5.3,270.0,1.1,0.0,22.5,0.0,12192.0,1016.4,0.0

In [ ]:
weathers2[weathers2['id'] == 1]

,id,time,temperature,humidity,wind_dir,wind_spd,cloudiness,pressure,precip_1h
0,1,2020-10-01T00:00:43+09:00,17.29,100.0,79.0,1.18,1.0,1012.0,0.0
1,1,2020-10-01T00:30:42+09:00,17.29,88.0,93.0,1.74,75.0,1011.0,0.0
2,1,2020-10-01T01:00:42+09:00,17.29,88.0,93.0,1.74,75.0,1011.0,0.0
3,1,2020-10-01T01:30:41+09:00,17.37,77.0,120.0,2.20,1.0,1012.0,0.0
4,1,2020-10-01T02:00:44+09:00,17.37,77.0,120.0,2.20,1.0,1012.0,0.0
...,...,...,...,...,...,...,...,...,...
35698,1,2022-10-23T21:30:41+09:00,11.48,50.0,300.0,2.06,0.0,1020.0,0.0
35699,1,2022-10-23T22:00:48+09:00,8.83,44.0,320.0,4.15,2.0,1021.0,0.0
35700,1,2022-10-23T22:30:41+09:00,10.52,57.0,290.0,3.09,0.0,1020.0,0.0
35701,1,2022-10-23T23:00:55+09:00,7.83,47.0,320.0,3.94,2.0,1021.0,0.0
35702,1,2022-10-23T23:30:42+09:00,10.16,57.0,280.0,2.06,0.0,1021.0,0.0

### weather + 발전량 매핑
* == 1. 태양광 발전소 목록 조회

* weather1, weather2, weather3의 차이 
* 각자 다른 지점에서

In [ ]:
import requests

pv_sites = requests.get(f'https://research-api.dershare.xyz/open-proc/cmpt-2022/pv-sites', headers={
                            'Authorization': f'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJSY3JocDhDb3dTdDllS2U0eWs2R0ZOIiwiaWF0IjoxNjY3Mzg2MTY0LCJleHAiOjE2Njg3ODM2MDAsInR5cGUiOiJhcGlfa2V5In0.n9v11Q633DaGIkWRVXz-46uf4Bx9L_YGAAbGzzGcgWs'
                        }).json()
pv_sites

[{'id': 0,
  'capacity': 472.39,
  'wth1_id': 1,
  'wth1_dist': 4539,
  'wth2_id': 1,
  'wth2_dist': 5486,
  'wth3_id': 1,
  'wth3_dist': 2497,
  'asos_station': 108,
  'asos_dist': 16196},
 {'id': 1,
  'capacity': 30.0,
  'wth1_id': 2,
  'wth1_dist': 1140,
  'wth2_id': 2,
  'wth2_dist': 1745,
  'wth3_id': 2,
  'wth3_dist': 867,
  'asos_station': 119,
  'asos_dist': 14969},
 {'id': 2,
  'capacity': 99.9,
  'wth1_id': 3,
  'wth1_dist': 429,
  'wth2_id': 3,
  'wth2_dist': 7929,
  'wth3_id': 3,
  'wth3_dist': 2054,
  'asos_station': 279,
  'asos_dist': 8111},
 {'id': 3,
  'capacity': 97.9,
  'wth1_id': 4,
  'wth1_dist': 355,
  'wth2_id': 4,
  'wth2_dist': 5562,
  'wth3_id': 4,
  'wth3_dist': 2391,
  'asos_station': 279,
  'asos_dist': 17267},
 {'id': 4,
  'capacity': 99.6,
  'wth1_id': 5,
  'wth1_dist': 870,
  'wth2_id': 4,
  'wth2_dist': 6749,
  'wth3_id': 5,
  'wth3_dist': 1735,
  'asos_station': 137,
  'asos_dist': 16766},
 {'id': 5,
  'capacity': 50.0,
  'wth1_id': 6,
  'wth1_dist': 1061,
  'wth2_id': 5,
  'wth2_dist': 2351,
  'wth3_id': 6,
  'wth3_dist': 2198,
  'asos_station': 156,
  'asos_dist': 6842},
 {'id': 6,
  'capacity': 70.0,
  'wth1_id': 7,
  'wth1_dist': 2228,
  'wth2_id': 6,
  'wth2_dist': 5921,
  'wth3_id': 7,
  'wth3_dist': 2380,
  'asos_station': 108,
  'asos_dist': 11351},
 {'id': 7,
  'capacity': 99.0,
  'wth1_id': 8,
  'wth1_dist': 633,
  'wth2_id': 7,
  'wth2_dist': 2297,
  'wth3_id': 8,
  'wth3_dist': 2382,
  'asos_station': 108,
  'asos_dist': 10633},
 {'id': 8,
  'capacity': 49.5,
  'wth1_id': 9,
  'wth1_dist': 574,
  'wth2_id': 1,
  'wth2_dist': 2026,
  'wth3_id': 9,
  'wth3_dist': 2014,
  'asos_station': 108,
  'asos_dist': 13931},
 {'id': 9,
  'capacity': 36.0,
  'wth1_id': 10,
  'wth1_dist': 377,
  'wth2_id': 8,
  'wth2_dist': 4254,
  'wth3_id': 10,
  'wth3_dist': 2481,
  'asos_station': 108,
  'asos_dist': 12626},
 {'id': 10,
  'capacity': 99.0,
  'wth1_id': 11,
  'wth1_dist': 190,
  'wth2_id': 9,
  'wth2_dist': 22494,
  'wth3_id': 11,
  'wth3_dist': 1525,
  'asos_station': 174,
  'asos_dist': 16968},
 {'id': 11,
  'capacity': 100.0,
  'wth1_id': 12,
  'wth1_dist': 752,
  'wth2_id': 10,
  'wth2_dist': 10761,
  'wth3_id': 12,
  'wth3_dist': 2761,
  'asos_station': 254,
  'asos_dist': 11498},
 {'id': 12,
  'capacity': 99.0,
  'wth1_id': 13,
  'wth1_dist': 510,
  'wth2_id': 9,
  'wth2_dist': 14308,
  'wth3_id': 13,
  'wth3_dist': 1876,
  'asos_station': 174,
  'asos_dist': 18284},
 {'id': 13,
  'capacity': 99.0,
  'wth1_id': 14,
  'wth1_dist': 1169,
  'wth2_id': 11,
  'wth2_dist': 11039,
  'wth3_id': 14,
  'wth3_dist': 1253,
  'asos_station': 156,
  'asos_dist': 19369},
 {'id': 14,
  'capacity': 100.0,
  'wth1_id': 15,
  'wth1_dist': 521,
  'wth2_id': 12,
  'wth2_dist': 3137,
  'wth3_id': 15,
  'wth3_dist': 2061,
  'asos_station': 252,
  'asos_dist': 5552},
 {'id': 15,
  'capacity': 97.9,
  'wth1_id': 16,
  'wth1_dist': 844,
  'wth2_id': 13,
  'wth2_dist': 10285,
  'wth3_id': 16,
  'wth3_dist': 2586,
  'asos_station': 260,
  'asos_dist': 26012},
 {'id': 16,
  'capacity': 99.0,
  'wth1_id': 17,
  'wth1_dist': 829,
  'wth2_id': 14,
  'wth2_dist': 12989,
  'wth3_id': 17,
  'wth3_dist': 3272,
  'asos_station': 165,
  'asos_dist': 14802},
 {'id': 17,
  'capacity': 365.0,
  'wth1_id': 18,
  'wth1_dist': 78,
  'wth2_id': 15,
  'wth2_dist': 11304,
  'wth3_id': 18,
  'wth3_dist': 1221,
  'asos_station': 156,
  'asos_dist': 9336},
 {'id': 18,
  'capacity': 97.2,
  'wth1_id': 19,
  'wth1_dist': 551,
  'wth2_id': 14,
  'wth2_dist': 19213,
  'wth3_id': 19,
  'wth3_dist': 2215,
  'asos_station': 268,
  'asos_dist': 18020},
 {'id': 19,
  'capacity': 300.0,
  'wth1_id': 20,
  'wth1_dist': 178,
  'wth2_id': 16,
  'wth2_dist': 2497,
  'wth3_id': 20,
  'wth3_dist': 461,
  'asos_station': 244,
  'asos_dist': 2219},
 {'id': 20,
  'capacity': 98.6,
  'wth1_id': 21,
  'wth1_dist': 1415,
  'wth2_id': 17,
  'wth2_dist': 4934,
  'wth3_id': 21,
  'wth3_dist': 2059,
  'asos_station': 129,
  'asos_dist': 2607}]

### gens와 weathers1 합치기

In [ ]:
len(gens[gens['id'] != 0]) # 361427

361427

In [ ]:
g = gens[gens['id'] != 0] # 광명시 일단 제외

In [ ]:
weathers1[weathers1['id'] == 1]['time'][0:25]
w = weathers1[weathers1['id'] != 1] # 광명시 날씨는 제외
w = w[1:] # w는 00시부터 시작하고 g는 01시부터 시작

In [ ]:
g

        id                       time  amount
2280     1  2020-10-01 01:00:00+09:00   0.000
2281     1  2020-10-01 02:00:00+09:00   0.000
2282     1  2020-10-01 03:00:00+09:00   0.000
2283     1  2020-10-01 04:00:00+09:00   0.000
2284     1  2020-10-01 05:00:00+09:00   0.000
...     ..                        ...     ...
363702  20  2022-10-23 20:00:00+09:00   0.008
363703  20  2022-10-23 21:00:00+09:00   0.008
363704  20  2022-10-23 22:00:00+09:00   0.008
363705  20  2022-10-23 23:00:00+09:00   0.008
363706  20  2022-10-24 00:00:00+09:00   0.008

[361427 rows x 3 columns]

In [ ]:
date = [] 
hour = []
g_time = list(g['time'])

for i, time in enumerate(g_time):
  date.append(time.split()[0]) # 날짜
  yet = time.split()[1]
  hour.append(yet.split(':')[0])

In [ ]:
list(g['time'])[0].split()[1].split(':')

['01', '00', '00+09', '00']

In [ ]:
g['date'] = date
g['hour'] = hour

In [ ]:
g

        id                       time  amount        date hour
2280     1  2020-10-01 01:00:00+09:00   0.000  2020-10-01   01
2281     1  2020-10-01 02:00:00+09:00   0.000  2020-10-01   02
2282     1  2020-10-01 03:00:00+09:00   0.000  2020-10-01   03
2283     1  2020-10-01 04:00:00+09:00   0.000  2020-10-01   04
2284     1  2020-10-01 05:00:00+09:00   0.000  2020-10-01   05
...     ..                        ...     ...         ...  ...
363702  20  2022-10-23 20:00:00+09:00   0.008  2022-10-23   20
363703  20  2022-10-23 21:00:00+09:00   0.008  2022-10-23   21
363704  20  2022-10-23 22:00:00+09:00   0.008  2022-10-23   22
363705  20  2022-10-23 23:00:00+09:00   0.008  2022-10-23   23
363706  20  2022-10-24 00:00:00+09:00   0.008  2022-10-24   00

[361427 rows x 5 columns]

In [ ]:
date = [] 
hour = []
w_time = list(w['time'])

for i, time in enumerate(w_time):
  date.append(time.split('T')[0]) # 날짜
  yet = time.split('T')[1]
  hour.append(yet.split(':')[0])

In [ ]:
w['date'] = date
w['hour'] = hour

In [ ]:
w

,id,time,temperature,humidity,dew_point,wind_dir,wind_spd,uv_idx,visibility,cloudiness,ceiling,pressure,precip_1h,date,hour
18820,2,2020-10-01T01:01:00+09:00,16.8,87.0,14.6,338.0,4.5,0.0,16.1,30.0,9144.0,1011.0,0.0,2020-10-01,01
18821,2,2020-10-01T02:01:00+09:00,16.4,95.0,15.6,45.0,4.5,0.0,12.9,8.0,9144.0,1012.0,0.0,2020-10-01,02
18822,2,2020-10-01T03:00:00+09:00,16.3,91.0,14.8,23.0,3.5,0.0,12.9,16.0,9144.0,1012.0,0.0,2020-10-01,03
18823,2,2020-10-01T04:00:00+09:00,15.7,89.0,13.9,158.0,4.5,0.0,16.1,76.0,9144.0,1012.0,0.0,2020-10-01,04
18824,2,2020-10-01T05:00:00+09:00,16.2,90.0,14.6,68.0,5.3,0.0,12.9,47.0,9144.0,1012.0,0.0,2020-10-01,05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403023,21,2022-10-23T20:58:00+09:00,12.9,67.0,6.9,293.0,9.4,0.0,48.3,0.0,12192.0,1020.4,0.0,2022-10-23,20
403024,21,2022-10-23T21:58:00+09:00,12.7,44.0,0.7,315.0,9.3,0.0,24.1,0.0,12192.0,1019.6,0.0,2022-10-23,21
403025,21,2022-10-23T22:07:00+09:00,12.9,43.0,0.7,315.0,9.3,0.0,49.9,0.0,12192.0,1019.9,0.0,2022-10-23,22
403026,21,2022-10-23T22:58:00+09:00,12.6,59.0,4.9,338.0,10.5,0.0,49.9,1.0,12192.0,1019.9,0.0,2022-10-23,22
403027,21,2022-10-23T23:58:00+09:00,11.0,71.0,5.9,315.0,5.4,0.0,49.9,2.0,12192.0,1019.3,0.0,2022-10-23,23

In [ ]:
Counter(list(w['date']))
# 개수가 다르고 중간에 없는 데이터도 존재

## merge

In [ ]:
# g

g_grop = []
for i in range(g.shape[0]):
  g_grop.append(str(g.iloc[i]['id']) + str(' / ') + str(g.iloc[i]['date']) + str(' / ') + str(g.iloc[i]['hour']))

In [ ]:
str(g.iloc[0]['id']) + str(' / ') + str(g.iloc[0]['date']) + str(' / ') + str(g.iloc[0]['hour'])

'1 / 2020-10-01 / 01'

In [ ]:
g['group'] = g_grop

In [ ]:
g

,id,time,amount,date,hour,group
2280,1,2020-10-01 01:00:00+09:00,0.000,2020-10-01,01,1 / 2020-10-01 / 01
2281,1,2020-10-01 02:00:00+09:00,0.000,2020-10-01,02,1 / 2020-10-01 / 02
2282,1,2020-10-01 03:00:00+09:00,0.000,2020-10-01,03,1 / 2020-10-01 / 03
2283,1,2020-10-01 04:00:00+09:00,0.000,2020-10-01,04,1 / 2020-10-01 / 04
2284,1,2020-10-01 05:00:00+09:00,0.000,2020-10-01,05,1 / 2020-10-01 / 05
...,...,...,...,...,...,...
363702,20,2022-10-23 20:00:00+09:00,0.008,2022-10-23,20,20 / 2022-10-23 / 20
363703,20,2022-10-23 21:00:00+09:00,0.008,2022-10-23,21,20 / 2022-10-23 / 21
363704,20,2022-10-23 22:00:00+09:00,0.008,2022-10-23,22,20 / 2022-10-23 / 22
363705,20,2022-10-23 23:00:00+09:00,0.008,2022-10-23,23,20 / 2022-10-23 / 23
363706,20,2022-10-24 00:00:00+09:00,0.008,2022-10-24,00,20 / 2022-10-24 / 00

In [ ]:
g_new = g[['id','date','hour','group','amount']]
g_new

        id        date hour                 group  amount
2280     1  2020-10-01   01   1 / 2020-10-01 / 01   0.000
2281     1  2020-10-01   02   1 / 2020-10-01 / 02   0.000
2282     1  2020-10-01   03   1 / 2020-10-01 / 03   0.000
2283     1  2020-10-01   04   1 / 2020-10-01 / 04   0.000
2284     1  2020-10-01   05   1 / 2020-10-01 / 05   0.000
...     ..         ...  ...                   ...     ...
363702  20  2022-10-23   20  20 / 2022-10-23 / 20   0.008
363703  20  2022-10-23   21  20 / 2022-10-23 / 21   0.008
363704  20  2022-10-23   22  20 / 2022-10-23 / 22   0.008
363705  20  2022-10-23   23  20 / 2022-10-23 / 23   0.008
363706  20  2022-10-24   00  20 / 2022-10-24 / 00   0.008

[361427 rows x 5 columns]

In [ ]:
# w

w_grop = []
for i in range(w.shape[0]):
  w_grop.append(str(w.iloc[i]['id']-1) + str(' / ') + str(w.iloc[i]['date']) + str(' / ') + str(w.iloc[i]['hour']))

In [ ]:
w['group'] = w_grop

In [ ]:
w

,id,time,temperature,humidity,dew_point,wind_dir,wind_spd,uv_idx,visibility,cloudiness,ceiling,pressure,precip_1h,date,hour,group
18820,2,2020-10-01T01:01:00+09:00,16.8,87.0,14.6,338.0,4.5,0.0,16.1,30.0,9144.0,1011.0,0.0,2020-10-01,01,1 / 2020-10-01 / 01
18821,2,2020-10-01T02:01:00+09:00,16.4,95.0,15.6,45.0,4.5,0.0,12.9,8.0,9144.0,1012.0,0.0,2020-10-01,02,1 / 2020-10-01 / 02
18822,2,2020-10-01T03:00:00+09:00,16.3,91.0,14.8,23.0,3.5,0.0,12.9,16.0,9144.0,1012.0,0.0,2020-10-01,03,1 / 2020-10-01 / 03
18823,2,2020-10-01T04:00:00+09:00,15.7,89.0,13.9,158.0,4.5,0.0,16.1,76.0,9144.0,1012.0,0.0,2020-10-01,04,1 / 2020-10-01 / 04
18824,2,2020-10-01T05:00:00+09:00,16.2,90.0,14.6,68.0,5.3,0.0,12.9,47.0,9144.0,1012.0,0.0,2020-10-01,05,1 / 2020-10-01 / 05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403023,21,2022-10-23T20:58:00+09:00,12.9,67.0,6.9,293.0,9.4,0.0,48.3,0.0,12192.0,1020.4,0.0,2022-10-23,20,20 / 2022-10-23 / 20
403024,21,2022-10-23T21:58:00+09:00,12.7,44.0,0.7,315.0,9.3,0.0,24.1,0.0,12192.0,1019.6,0.0,2022-10-23,21,20 / 2022-10-23 / 21
403025,21,2022-10-23T22:07:00+09:00,12.9,43.0,0.7,315.0,9.3,0.0,49.9,0.0,12192.0,1019.9,0.0,2022-10-23,22,20 / 2022-10-23 / 22
403026,21,2022-10-23T22:58:00+09:00,12.6,59.0,4.9,338.0,10.5,0.0,49.9,1.0,12192.0,1019.9,0.0,2022-10-23,22,20 / 2022-10-23 / 22
403027,21,2022-10-23T23:58:00+09:00,11.0,71.0,5.9,315.0,5.4,0.0,49.9,2.0,12192.0,1019.3,0.0,2022-10-23,23,20 / 2022-10-23 / 23

In [ ]:
w_new = w[['id','date','hour','group','temperature','humidity','dew_point','wind_dir',
           'wind_spd','uv_idx','visibility','cloudiness','ceiling','pressure','precip_1h']]
w_new

,id,date,hour,group,temperature,humidity,dew_point,wind_dir,wind_spd,uv_idx,visibility,cloudiness,ceiling,pressure,precip_1h
18820,2,2020-10-01,01,1 / 2020-10-01 / 01,16.8,87.0,14.6,338.0,4.5,0.0,16.1,30.0,9144.0,1011.0,0.0
18821,2,2020-10-01,02,1 / 2020-10-01 / 02,16.4,95.0,15.6,45.0,4.5,0.0,12.9,8.0,9144.0,1012.0,0.0
18822,2,2020-10-01,03,1 / 2020-10-01 / 03,16.3,91.0,14.8,23.0,3.5,0.0,12.9,16.0,9144.0,1012.0,0.0
18823,2,2020-10-01,04,1 / 2020-10-01 / 04,15.7,89.0,13.9,158.0,4.5,0.0,16.1,76.0,9144.0,1012.0,0.0
18824,2,2020-10-01,05,1 / 2020-10-01 / 05,16.2,90.0,14.6,68.0,5.3,0.0,12.9,47.0,9144.0,1012.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403023,21,2022-10-23,20,20 / 2022-10-23 / 20,12.9,67.0,6.9,293.0,9.4,0.0,48.3,0.0,12192.0,1020.4,0.0
403024,21,2022-10-23,21,20 / 2022-10-23 / 21,12.7,44.0,0.7,315.0,9.3,0.0,24.1,0.0,12192.0,1019.6,0.0
403025,21,2022-10-23,22,20 / 2022-10-23 / 22,12.9,43.0,0.7,315.0,9.3,0.0,49.9,0.0,12192.0,1019.9,0.0
403026,21,2022-10-23,22,20 / 2022-10-23 / 22,12.6,59.0,4.9,338.0,10.5,0.0,49.9,1.0,12192.0,1019.9,0.0
403027,21,2022-10-23,23,20 / 2022-10-23 / 23,11.0,71.0,5.9,315.0,5.4,0.0,49.9,2.0,12192.0,1019.3,0.0

In [ ]:
Counter(list(w['group'])).most_common(10)

[('1 / 2022-10-12 / 12', 4),
 ('9 / 2022-09-22 / 16', 4),
 ('20 / 2022-10-03 / 05', 4),
 ('1 / 2021-12-04 / 08', 3),
 ('1 / 2021-12-07 / 03', 3),
 ('1 / 2021-12-09 / 05', 3),
 ('1 / 2021-12-09 / 20', 3),
 ('1 / 2021-12-09 / 21', 3),
 ('1 / 2022-01-07 / 20', 3),
 ('1 / 2022-01-17 / 02', 3)]

In [ ]:
'''
1. weather과 amount를 날짜를 기준으로 합친다. : 예측은 weather과 amount만을 기준으로
2. 시간을 기준으로 여러개의 테이블을 만든다. : 시간대별로 모델을 알아서 돌리면 되니까
3. 그리고 시간대별로 테이블을 학습시켜서 모델을 만든다.
4. 시간대에 맞춰서 날씨 데이터를 넣으면 input으로서 결과가 나온다.

# 시간대 + 날씨 이면 굳이 연월을 넣는 것보다 효과적일 것으로 예상된다.
'''

#

In [ ]:
w_new.head(5)

,id,date,hour,group,temperature,humidity,dew_point,wind_dir,wind_spd,uv_idx,visibility,cloudiness,ceiling,pressure,precip_1h
18820,2,2020-10-01,01,1 / 2020-10-01 / 01,16.8,87.0,14.6,338.0,4.5,0.0,16.1,30.0,9144.0,1011.0,0.0
18821,2,2020-10-01,02,1 / 2020-10-01 / 02,16.4,95.0,15.6,45.0,4.5,0.0,12.9,8.0,9144.0,1012.0,0.0
18822,2,2020-10-01,03,1 / 2020-10-01 / 03,16.3,91.0,14.8,23.0,3.5,0.0,12.9,16.0,9144.0,1012.0,0.0
18823,2,2020-10-01,04,1 / 2020-10-01 / 04,15.7,89.0,13.9,158.0,4.5,0.0,16.1,76.0,9144.0,1012.0,0.0
18824,2,2020-10-01,05,1 / 2020-10-01 / 05,16.2,90.0,14.6,68.0,5.3,0.0,12.9,47.0,9144.0,1012.0,0.0

In [ ]:
g_new.head(5)

      id        date hour                group  amount
2280   1  2020-10-01   01  1 / 2020-10-01 / 01     0.0
2281   1  2020-10-01   02  1 / 2020-10-01 / 02     0.0
2282   1  2020-10-01   03  1 / 2020-10-01 / 03     0.0
2283   1  2020-10-01   04  1 / 2020-10-01 / 04     0.0
2284   1  2020-10-01   05  1 / 2020-10-01 / 05     0.0

In [ ]:
Counter(list(g_new['group'])).most_common(3)

[('1 / 2020-10-01 / 01', 1),
 ('1 / 2020-10-01 / 02', 1),
 ('1 / 2020-10-01 / 03', 1)]

In [ ]:
w_new

,id,date,hour,group,temperature,humidity,dew_point,wind_dir,wind_spd,uv_idx,visibility,cloudiness,ceiling,pressure,precip_1h
18820,2,2020-10-01,01,1 / 2020-10-01 / 01,16.8,87.0,14.6,338.0,4.5,0.0,16.1,30.0,9144.0,1011.0,0.0
18821,2,2020-10-01,02,1 / 2020-10-01 / 02,16.4,95.0,15.6,45.0,4.5,0.0,12.9,8.0,9144.0,1012.0,0.0
18822,2,2020-10-01,03,1 / 2020-10-01 / 03,16.3,91.0,14.8,23.0,3.5,0.0,12.9,16.0,9144.0,1012.0,0.0
18823,2,2020-10-01,04,1 / 2020-10-01 / 04,15.7,89.0,13.9,158.0,4.5,0.0,16.1,76.0,9144.0,1012.0,0.0
18824,2,2020-10-01,05,1 / 2020-10-01 / 05,16.2,90.0,14.6,68.0,5.3,0.0,12.9,47.0,9144.0,1012.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403023,21,2022-10-23,20,20 / 2022-10-23 / 20,12.9,67.0,6.9,293.0,9.4,0.0,48.3,0.0,12192.0,1020.4,0.0
403024,21,2022-10-23,21,20 / 2022-10-23 / 21,12.7,44.0,0.7,315.0,9.3,0.0,24.1,0.0,12192.0,1019.6,0.0
403025,21,2022-10-23,22,20 / 2022-10-23 / 22,12.9,43.0,0.7,315.0,9.3,0.0,49.9,0.0,12192.0,1019.9,0.0
403026,21,2022-10-23,22,20 / 2022-10-23 / 22,12.6,59.0,4.9,338.0,10.5,0.0,49.9,1.0,12192.0,1019.9,0.0
403027,21,2022-10-23,23,20 / 2022-10-23 / 23,11.0,71.0,5.9,315.0,5.4,0.0,49.9,2.0,12192.0,1019.3,0.0

In [ ]:
total_df = pd.merge(w_new, g_new[['group','amount']], on='group', how='left')
total_df

,id,date,hour,group,temperature,humidity,dew_point,wind_dir,wind_spd,uv_idx,visibility,cloudiness,ceiling,pressure,precip_1h,amount
0,2,2020-10-01,01,1 / 2020-10-01 / 01,16.8,87.0,14.6,338.0,4.5,0.0,16.1,30.0,9144.0,1011.0,0.0,0.000
1,2,2020-10-01,02,1 / 2020-10-01 / 02,16.4,95.0,15.6,45.0,4.5,0.0,12.9,8.0,9144.0,1012.0,0.0,0.000
2,2,2020-10-01,03,1 / 2020-10-01 / 03,16.3,91.0,14.8,23.0,3.5,0.0,12.9,16.0,9144.0,1012.0,0.0,0.000
3,2,2020-10-01,04,1 / 2020-10-01 / 04,15.7,89.0,13.9,158.0,4.5,0.0,16.1,76.0,9144.0,1012.0,0.0,0.000
4,2,2020-10-01,05,1 / 2020-10-01 / 05,16.2,90.0,14.6,68.0,5.3,0.0,12.9,47.0,9144.0,1012.0,0.0,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384203,21,2022-10-23,20,20 / 2022-10-23 / 20,12.9,67.0,6.9,293.0,9.4,0.0,48.3,0.0,12192.0,1020.4,0.0,0.008
384204,21,2022-10-23,21,20 / 2022-10-23 / 21,12.7,44.0,0.7,315.0,9.3,0.0,24.1,0.0,12192.0,1019.6,0.0,0.008
384205,21,2022-10-23,22,20 / 2022-10-23 / 22,12.9,43.0,0.7,315.0,9.3,0.0,49.9,0.0,12192.0,1019.9,0.0,0.008
384206,21,2022-10-23,22,20 / 2022-10-23 / 22,12.6,59.0,4.9,338.0,10.5,0.0,49.9,1.0,12192.0,1019.9,0.0,0.008
384207,21,2022-10-23,23,20 / 2022-10-23 / 23,11.0,71.0,5.9,315.0,5.4,0.0,49.9,2.0,12192.0,1019.3,0.0,0.008

In [ ]:
total_df.to_csv('/content/drive/MyDrive/POSTECH 태양광 발전량 예측/DATA/total_df.csv',sep=',', na_rep='NaN')